extend split_data_by_task()
mkim425/modelimportance pull request #25
Opened 2024-12-17 21:01 UTC by mkim425

Extended function to handle both untrained and trained ensembles

- Updated logic to support trained ensemble scenarios.
- Preserved existing functionality for untrained ensembles.

2025-02-14 15:42 UTC, nickreich commented on DESCRIPTION
> +    hubEnsembles
maybe worth confirming whether you are relying on a minimum specific version of these packages.

2025-02-14 15:49 UTC, nickreich commented on R/model_importance.R
> +
consider adding some pseudo-code or prototype code (in comments is ok, if lintr is complaining) to show what the eventual structure of this function might look like.

2025-02-14 15:51 UTC, nickreich commented on R/score_untrained.R
> +#' `mean`, `median`, `quantile`, or `pmf`.
consider adding sample as a valid output_type. Would mean you would have to align that output type with valid scores.

2025-02-14 15:54 UTC, nickreich commented on R/score_untrained.R
> +#' an `output_type` of `mean`, `quantile`, or `pmf`.
would want to add sample here, if you add it.

2025-02-14 15:57 UTC, nickreich commented on R/score_untrained.R
> +#' @param subset_wt A character string specifying method for assigning weight
if this is the same argument as in model_importance() there may be a way to "inherit" the params arguments using Roxygen. worth looking into.

2025-02-14 15:58 UTC, nickreich commented on R/score_untrained.R
> +#' one of the following: `se_point`, `ae_point`, `wis`, or `log_score`.
consider modifying for sample output type

2025-02-14 19:57 UTC, mkim425 commented on R/score_untrained.R
> +#' @param subset_wt A character string specifying method for assigning weight
I like this inheritance of documentation. It’s so convenient!

2025-03-10 17:29 UTC, nickreich requested changes
Hi @mkim425 - Thanks for this next round of code for this package. It's looking really good! I have a handful of smaller comments, but then a few that I'd like to highlight as being potentially more complex/important to address:

 - are some of the task-id variable names hard-coded? I think in general, we want these to be user-specified.
 - one comment in split_data_by_task.R that might be incorrect in terms of indexing.
 - typo in a variable name
 - use of `first()` which introduces an implicit dependency on ordering of rows, which feels dangerous to me.

2025-03-10 17:29 UTC, nickreich commented on R/model_importance.R
> +#' @param subset_wt A character string specifying method for assigning weight
is this argument optional? if so, say so explicitly here.

2025-03-10 17:29 UTC, nickreich commented on R/score_untrained.R
> +#' `mean`, `median`, `quantile`, or `pmf`.
We are not going to do this now, since hubEvals does not support sample output types.

2025-03-10 17:29 UTC, nickreich commented on R/score_untrained.R
> +        importance = .data$calculated_metric - first(.data$calculated_metric)
Does this line's use of `first()` rely on the ordering of rows in the data? if so, I suggest making this line more explicit, so that if the code above changes at a later point and the data are re-ordered, it would not change the output.

2025-03-10 17:29 UTC, nickreich commented on R/score_untrained.R
> +        model_id = "enseble-all"
this should be "ensemble-all" not "enseble-all". This error is repeated in a few places in this file.

2025-03-10 17:29 UTC, nickreich commented on R/score_untrained.R
> +    importance_scores <- bind_rows(df_importance, new_rows)
I wonder if there is a less manual way of doing this using something like expand_grid() and left_join()? That said, if this works, maybe it's ok as is.

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
>  #' @examples \dontrun{
if you are not exporting this function, then I'm not sure you need an example for it

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +  training_status <- ifelse(weighted, "trained", "untrained")
I'm not sure why we need this new variable. can't we just use the weighted as the indicator in the if else statement below?

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +    split_cols <- c("horizon", "location", "target_end_date")
Do we have a guarantee that these columns will be present in all datasets? Generally, these column names are not required, and the names could be anything.

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +    all_ref_dates <- sort(unique(valid_tbl$reference_date))
same comment as just above - it seems dangerous to standardize on a specific task-id variable name.

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +      }
I remember learning something a long time ago about how this kind of recursive assignment/creation of objects can be an inefficient use of memory. It may be fine here, but I could imagine there might be long lists of a lot of data, so it might be the kind of thing where it could matter. This is a place where @matthewcornell might have suggestions of whether there might be a better way of structuring the code.

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +            .data$reference_date >= all_ref_dates[i]
I think that this might return `training_window_length+1` dates, not `training_window_length` dates.
``` r
tmp <- seq.Date(from = as.Date("2025-01-01"), 
                to = as.Date("2025-12-31"), 
                by=7)
i = 5
training_window_length = 7
sum(tmp >= tmp[i] & tmp <= tmp[i+training_window_length])
## this returns 8
```

2025-03-10 17:29 UTC, nickreich commented on R/split_data_by_task.R
> +            .data$reference_date >= all_ref_dates[i]
is that the desired behavior?

2025-03-10 17:29 UTC, nickreich commented on R/validate_input_data.R
>  #' @import dplyr
same comment as in a previous file. Are examples needed if this function is not exported?

2025-03-10 17:29 UTC, nickreich commented on tests/testthat/test-score_untrained.R
> +  expected_importance <- (se_ensemble - se_ensemble[1])[-1]
Some additional code comments in this section would help an uninitiated reader understand the calculations you are doing here.

2025-03-10 17:29 UTC, nickreich commented on tests/testthat/test-score_untrained.R
These tests seem important and useful! One additional test that I could imagine would be valuable to add is to ensure that the computations are correct when one task is missing for a model, but not all tasks are missing. Is the function applying the correct penalization for when it is missing, and summarizing appropriately? That is kind of what the "Assign NAs for missing data" test is doing, but I guess I was thinking about the next step of summarization of importance scores too.

2025-03-10 17:29 UTC, nickreich commented on tests/testthat/test-split_data_by_task.R
> +  split_cols <- c("horizon", "location", "target_end_date")
I again have a concern about expecting these specific task-id variable names.

2025-03-10 17:33 UTC, matthewcornell approved these changes, later dismissed
Hi Minsu. Nick asked me to review this PR. Generally it looks good to me so far. I have two questions about the status:

- IIUC, model_importance() will dispatch to one of two scoring functions: score_untrained() (which is implemented and tested) and something like score_trained() and test-score_untrained.R (which are TBD), correct?
- Also, I couldn't find score_model_out() - is it (and its tests) also TBD?

Looking good!

2025-03-10 17:50 UTC, matthewcornell commented on R/split_data_by_task.R
> +      }
Good question, Nick. I'm not familiar with R's efficiency of loops like the for() vs. dplyer and other dataframe operations. I believe the latter are faster, but I'm not 100% sure.

2025-03-10 19:13 UTC, zkamvar commented on R/split_data_by_task.R
> +      }
You can use a for loop syntax if you pre-allocate the list. Mapping or dplyr operations are not necessarily going to be better or faster for this operation. 


```suggestion
      n_dates <- len_ref_dates - training_window_length
      list_datasets <- vector(mode = "list", length = n_dates)
      for (i in seq_len(n_dates)) {
        list_datasets[[i]] <- valid_tbl |>
          dplyr::filter(
            .data$reference_date <= all_ref_dates[i + training_window_length],
            .data$reference_date >= all_ref_dates[i]
          )
      }
```

2025-03-10 20:02 UTC, nickreich commented on R/split_data_by_task.R
> +      }
Thanks @zkamvar . Just to clarify, one "could" do this either way (the way Minsu has it currently coded, or your suggested way) but you recommend the pre-allocation for more efficient memory handling?

2025-03-10 20:04 UTC, rogersbw commented on R/split_data_by_task.R
> +      }
I would think a parallelized operation should be more efficient.

But if I'm understanding the workflow here, the final list has a lot of repeat data, correct? Then something is done to each of the data frames in the list?

Maybe you could make the inside of that for() loop a function which takes an index and a training_window_length and then apply that in parallel, or create the data frames at a time and then operate on each data frame as needed, then discard and on to the next, so you're holding so much repeat data in memory.

2025-03-10 20:54 UTC, zkamvar commented on R/split_data_by_task.R
> +      }
> but you recommend the pre-allocation for more efficient memory handling?

Yes. I will also note that my proposal also fixes the `1:n` form of generating a sequence, [which can have problems if `n` is zero](https://lintr.r-lib.org/reference/seq_linter.html).

2025-03-20 19:06 UTC, mkim425 commented on R/score_untrained.R
> +    importance_scores <- bind_rows(df_importance, new_rows)
I rewrote this part. I couldn't figure out the code with expand_grid() and left_join() to generate the data frame I wanted, but the new code is simple enough.

2025-03-20 19:47 UTC, mkim425 commented on R/split_data_by_task.R
> +            .data$reference_date >= all_ref_dates[i]
Yes, that's what I desired. The dataset includes 8 dates, and the data are split into two components when building ensembles and calculating importance scores; the most recent date is considered the "current time," and the dataset corresponding to the other 7 dates will be a training set to be used for estimating model weights.

2025-03-20 20:06 UTC, mkim425 commented on R/split_data_by_task.R
> +      }
Hi everyone, thank you all so much for this discussion! I truly appreciate each of you. 
@zkamvar, Thanks a lot for your code. I replaced my code with yours.

2025-03-20 20:56 UTC, mkim425 commented
> Hi Minsu. Nick asked me to review this PR. Generally it looks good to me so far. I have two questions about the status:
> 
> * IIUC, model_importance() will dispatch to one of two scoring functions: score_untrained() (which is implemented and tested) and something like score_trained() and test-score_untrained.R (which are TBD), correct?
> * Also, I couldn't find score_model_out() - is it (and its tests) also TBD?
> 
> Looking good!

Hi Matt, thank you very much for reviewing my code. Here are my responses to your questions. 
- Your understanding is correct. `score_untrained()` and `score_trained()` are subfunctions within the main function `model_importance()`. Currently, forecast_data is assigned to score_result, but I will replace it later with the calculation results from either `score_untrained()` or `score_trained()`.  
- score_model_out() is a function in the `hubEvals` package.

2025-03-20 21:33 UTC, zkamvar commented on R/score_untrained.R
> +      )
A small note about the switch statements you have here: since the arguments of both function calls are the same, you can extract the function from the `hubEnsembles` package and apply it to reduce duplication. 

```suggestion
    # `ENS_FUN` is a function from hubEnsembles specified by `ensemble_fun` 
    ENS_FUN <- getFromNamespace(ensemble_fun, ns = asNamespace("hubEnsembles"))
    ens_all <- ENS_FUN(single_task_data,
      weights = NULL,
      model_id = "ensemble-all"
    )

    # build ensemble forecasts by leaving one model out
    ens_lomo <- lapply(models, function(x) {
      single_task_data_lomo <- single_task_data |>
        dplyr::filter(.data$model_id != x) |>
        ENS_FUN(
          weights = NULL,
          model_id = paste0("ens.wo.", x)
        )
```

2025-03-20 22:02 UTC, mkim425 commented on R/score_untrained.R
> +      )
@zkamvar Wow, this is fantastic! Thank you for it!

2025-03-24 16:02 UTC, mkim425 commented on R/split_data_by_task.R
> +    all_ref_dates <- sort(unique(valid_tbl$reference_date))
Hi @nickreich, Could you explain this? I don't understand why it seems dangerous. 
To help you recall, in `validate_input_data.R` [here](https://github.com/mkim425/modelimportance/blob/8441a64710c0b133705a1819807c04f206e58646/R/validate_input_data.R#L38), I check if there is a column representing the forecast date and require to have only one column for it. Otherwise, I give a message to do so.

2025-03-24 16:23 UTC, mkim425 commented on tests/testthat/test-score_untrained.R
If a model misses all tasks, it won't be in the `model_id_list` extracted from the input forecast data, and it should have made at least one prediction to be on that list.  `score_untrained()` calculates the importance for a single task based on that model list.

2025-03-24 19:40 UTC, nickreich commented on R/split_data_by_task.R
> +    all_ref_dates <- sort(unique(valid_tbl$reference_date))
I see. I agree that you have this requirement and that this is not "dangerous".

2025-03-24 19:43 UTC, nickreich commented on R/split_data_by_task.R
> +    all_ref_dates <- sort(unique(valid_tbl$reference_date))
I guess I do think it would be useful somewhere to state this assumption/requirement explicitly in the documentation. Something like:
"This function requires that one column represent the forecast date (or a date from which each forecast originates or is made in reference to) and that it be named one of XX, YY, or ZZ"

2025-03-25 18:45 UTC, nickreich approved these changes
I have one small follow-up comment but otherwise it looks good to me.

2025-03-25 18:45 UTC, nickreich commented on tests/testthat/test-score_untrained.R
I see, so maybe my comment applies to a higher level function that is summarizing across multiple tasks?

2025-03-27 14:14 UTC, merged